name: 'Terraform setup and plan'
description: 'Setup Terraform and creates plan'
inputs:
  terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
  tfcloud_api_token:
    description: 'TF Cloud API token for remote statefile'
    required: true
  terraform_grafana_api_token:
    description: 'Grafana API token'
    required: true
  terraform_grafana_url:
    description: 'Grafana Cloud URL'
    required: true
  terraform_version:
    description: 'Terraform Version'
    required: true
    default: 1.7.3
  github_token:
    description: 'GitHub token for auth'
    required: true
  pr_id:
    description: 'Pull request ID'
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses:  hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false
        cli_config_credentials_token: ${{ inputs.tfcloud_api_token }}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        terraform init

    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        echo 'plan<<EOF' >> $GITHUB_OUTPUT
        terraform plan -input=false -no-color -out=tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      env:
        TF_VAR_GRAFANA_AUTH: ${{ inputs.terraform_grafana_api_token }}
        TF_VAR_GRAFANA_URL: ${{ inputs.terraform_grafana_url }}

    - name: Save Artifact
      id: save-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.pr_id }}-tf-plan
        path: ${{ inputs.terraform_directory }}/tfplan

    - name: Comment Plan
      id: comment-plan
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_id }}
        body: |
          Terraform Plan:

          ```
          ${{ steps.plan.outputs.plan }}
          ```

          Plan saved to GH artifacts.
