name: "Terraform setup and apply"
description: "Applys a terraform plan file from an artifact"
inputs:
  terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
  tfcloud_api_token:
    description: 'TF Cloud API token for remote statefile'
    required: true
  terraform_grafana_api_token:
    description: 'Grafana API token'
    required: true
  terraform_grafana_url:
    description: 'Grafana Cloud URL'
    required: true
  terraform_version:
    description: 'Terraform Version'
    required: true
    default: 1.7.3
  github_token:
    description: 'GitHub token for auth'
    required: true
  pr_id:
    description: 'Pull request ID'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses:  hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false
        cli_config_credentials_token: ${{ inputs.tfcloud_api_token }}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        terraform init

    - name: Download Plan
      id: download-plan
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ inputs.github_token }}
        workflow: plan.yml
        pr: ${{ inputs.pr_id }}
        name: ${{ inputs.pr_id }}-tf-plan
        path: ${{ inputs.terraform_directory }}

    - name: Terraform Apply
      id: apply
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        echo 'apply<<EOF' >> $GITHUB_OUTPUT
        terraform apply -input=false -no-color tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      env:
        TF_VAR_GRAFANA_AUTH: ${{ inputs.terraform_grafana_api_token }}
        TF_VAR_GRAFANA_URL: ${{ inputs.terraform_grafana_url }}

    - name: Comment Apply
      id: comment-apply
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_id }}
        body: |
          Terraform Apply:

          ```
          ${{ steps.apply.outputs.apply }}
          ```
