name: "Terraform setup and destroy"
description: "Destroys terraform resources"
inputs:
  terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
  tfcloud_api_token:
    description: 'TF Cloud API token for remote statefile'
    required: true
  terraform_grafana_api_token:
    description: 'Grafana API token'
    required: true
  terraform_grafana_url:
    description: 'Grafana Cloud URL'
    required: true
  terraform_version:
    description: 'Terraform Version'
    required: true
    default: 1.7.3


runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false
        cli_config_credentials_token: ${{ inputs.tfcloud_api_token }}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        terraform init

    - name: Terraform Destroy
      id: destroy
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        terraform destroy -auto-approve
      env:
        TF_VAR_GRAFANA_AUTH: ${{ inputs.terraform_grafana_api_token }}
        TF_VAR_GRAFANA_URL: ${{ inputs.terraform_grafana_url }}
