name: Terraform Apply

on:
  pull_request_review:
    types:
      - submitted

env:
  TERRAFORM_VERSION: "1.7.3"
  TF_IN_AUTOMATION: "True"

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    environment: test
    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@v3

      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ inputs.github_ref }}
        run: |
          echo "GITHUB_REF: " $GITHUB_REF
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        uses: ./.github/apply
        with:
          terraform_directory: "terraform"
          tfcloud_api_token: ${{ secrets.TF_TFCLOUD_TOKEN }}
          terraform_grafana_api_token: ${{ secrets.TF_GRAFANA_AUTH }}
          terraform_grafana_url: ${{ variables.TF_GRAFANA_URL }}
          github_token: ${{ secrets.GH_TOKEN }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
